### ISSUE TITLE
Not responding after some days - need to restart Homebridge

### ISSUE THREAD

**Issue by acresp** [fdegier/homebridge-jablotron-alarm#73] opened 2022-03-14 12:39 UTC
Hello,
I don't know if there were some changes recently that could be the reason, but I keep the plugin up to date as much as possible.
And since few weeks, I noticed that the plugin does not respond anymore after few days, I need to restart Homebridge to get it working again.
And here is the error I see in Homebridge when the plugin does not work:

`[3/14/2022, 1:35:33 PM] [Jablotron] Error: TypeError: Cannot read properties of undefined (reading '0')
[3/14/2022, 1:35:33 PM] [Jablotron] Unable to parse JSON
[3/14/2022, 1:36:33 PM] [Jablotron] Error: TypeError: Cannot read properties of undefined (reading '0')
[3/14/2022, 1:36:33 PM] [Jablotron] Unable to parse JSON`

Thanks for your help :-)

**Comment by fdegier** [comment] 2022-03-14 12:40
Hi, I just noticed as well. Jablotron has been doing some maintenance / work on their API and it seems to have broken this plugin. Last week the update was to upgrade from 1.6 to 1.8 but it seems one of the data structures has changed now. Hang tight, working on it.

**Comment by fdegier** [comment] 2022-03-14 12:48
*Interim solution*
Restart your homebridge. 



Interesting, so originally I did not read your message fully as I thought the issue was on Jablotron side again as they had maintenance over the weekend. When I restarted my homebridge it also starting working again so it seems to be that we have the exact same issue. 

Will need to dive deeper into this issue later, tagging @misncz for awareness.

**Comment by misncz** [comment] 2022-03-14 13:07
Yes, this is what happened to me and other guy too. I haven't seen this error till then. I raised PR to add enhanced error handling that might explain what's going on. I just hope Jablotron isn't moving to API 1.9 as that's quite different

**Comment by fdegier** [comment] 2022-03-17 22:26
I finally got the issue again and the error is quite clear. Seems like a regression. 

![image](https://user-images.githubusercontent.com/13218917/158904449-90d84359-9a82-42e6-994f-5dde2ac451b1.jpeg)

**Comment by misncz** [comment] 2022-03-17 22:29
Looks like cloud now invalidates sessions after some time

**Comment by misncz** [comment] 2022-03-18 08:05
@fdegier I raised PR with the fix

**Comment by fdegier** [comment] 2022-03-18 10:08
Fixed in #75

**Closed by fdegier** 2022-03-18 10:08 UTC

**Comment by acresp** [comment] 2022-03-18 10:34
Thanks a lot for your work!! @misncz @fdegier
