### ISSUE TITLE
Add thermometers

### ISSUE THREAD

**Issue by dfridrich** [fdegier/homebridge-jablotron-alarm#64] opened 2022-01-20 18:36 UTC
It would be great if this Homebridge extension would also show temperature senzors (they are accessible from jablonet.net).

![image](https://user-images.githubusercontent.com/3758421/150400855-75196afe-1e51-44b4-9053-5e3792a82e98.png)

**Comment by fdegier** [comment] 2022-01-20 18:51
That would be awesome indeed, I do not have any temperature sensors unfortunately. Would you be able to help?

**Comment by misncz** [comment] 2022-01-20 21:23
Are you using wired (to bus) or wireless sensors?

**Comment by dfridrich** [comment] 2022-01-22 13:02
> Are you using wired (to bus) or wireless sensors?

I am using all wired.

**Comment by misncz** [comment] 2022-01-22 16:13
> > Are you using wired (to bus) or wireless sensors?
> 
> I am using all wired.

Ok. My friend can loan me one so I give it a try and will see what we can do to support them

**Comment by dfridrich** [comment] 2022-01-23 00:48
> > > Are you using wired (to bus) or wireless sensors?
> 
> > 
> 
> > I am using all wired.
> 
> 
> 
> Ok. My friend can loan me one so I give it a try and will see what we can do to support them

If you'll need any help, don't hesitate to contact me as well. Good luck ;-)

**Comment by misncz** [comment] 2022-02-26 18:25
@dfridrich I implemented support for thermometers (not thermostats as I don't have any) and raised a pull request. Enjoy once it gets merged and released by @fdegier

**Comment by misncz** [comment] 2022-02-26 18:30
@dfridrich you need to run config helper to receive thermometers config to be added to homebridge

**Comment by fdegier** [comment] 2022-02-27 11:10
Released in `v2.4.0`

**Closed by fdegier** 2022-02-27 11:10 UTC

**Comment by dfridrich** [comment] 2022-04-11 18:28
@misncz thanks for great job! Is there possibility to add thermostats too? It would be very useful.

**Comment by misncz** [comment] 2022-04-12 08:31
@dfridrich unfortunately I don't have any thermostats available to be able to do that

**Comment by misncz** [comment] 2022-04-17 07:33
@dfridrich looks like I'll be able to get one thermostat for testing the week after next one. I let you know if I'm able to progress then

**Comment by dfridrich** [comment] 2022-04-18 20:06
@misncz thanks, if you would to have some more thermostats for test, I could provide some.

**Comment by misncz** [comment] 2022-08-29 09:45
@dfridrich yes I did. I'm able to read current temperature only (not temperature set on thermostat). The problem is that to be able to read/control more thermostat options we'd need to upgrade Jablotron API version which is not an easy task. With currently implemented API version the thermostat functionality is limited to thermometer which is not what you'd like to have I assume

CC: @fdegier
